### ISSUE TITLE
Instant Articles falls over if `unwrap_image` tries to unwrap image from some elements

### ISSUE THREAD

**Issue by sparkdevelopment** [WPArtisan/wp-native-articles#1]
In this case, it was an `<li>` element with an image in in, had to replace the condition with 
```
if ( ! $node || 'a' !== $node->nodeType ) {
```
at 
https://github.com/WPArtisan/wp-native-articles/blob/9a97a64013e023d67b3c68b21aaaf6ff56101e77/includes/class-facebook-content-parser-v2.php#L783

**Comment by sparkdevelopment** [comment]
Actually, might just need to unhook `unwrap_image` from `wpna_facebook_article_content_transform_node_li`...

**Comment by ozthegreat** [comment]
@sparkdevelopment can you send me the Text tab source of the post that's the issue and I'll try and reproduce.

**Comment by sparkdevelopment** [comment]
https://gist.github.com/sparkdevelopment/53a65f93c88d0ba5e9ecbe01062155b3

I think it's L44 that's causing the issue

**Comment by ozthegreat** [comment]
Done in v1.5.3 (released today)
